// <auto-generated />
namespace Anyware.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedProductInOrder : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedProductInOrder));
        
        string IMigrationMetadata.Id
        {
            get { return "202101141803590_addedProductInOrder"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
